name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.0.3
homepage: https://github.com/Baseflow/flutter_cached_network_image
publish_to: none
environment:
  sdk: ^3.1.0
  flutter: '>=3.13.0'

dependencies:
  cached_network_image_platform_interface:
    git: https://github.com/sumitsharansatsangi/cached_network_image_platform_interface.git
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git: 
      url: https://github.com/sumitsharansatsangi/flutter_cache_manager.git
      path: flutter_cache_manager

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  flutter_test:
    sdk: flutter
