name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
publish_to: none  
version: 3.2.4
environment:
  sdk: ^3.1.0
  flutter: '>=3.13.0'

dependencies:
  cached_network_image_platform_interface:
    git: https://github.com/sumitsharansatsangi/cached_network_image_platform_interface.git
  cached_network_image_web:
    git: https://github.com/sumitsharansatsangi/cached_network_image_web.git
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git: 
      url: https://github.com/sumitsharansatsangi/flutter_cache_manager.git
      path: flutter_cache_manager
  octo_image: ^1.0.2

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
