name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.3
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git: 
      url: https://github.com/sumitsharansatsangi/flutter_cache_manager.git
      path: ./flutter_cache_manager
  octo_image: ^1.0.2
  cached_network_image_platform_interface:
    path: ../cached_network_image_platform_interface
  cached_network_image_web:
    path: ../cached_network_image_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.2
  file: ^6.1.4

environment:
  flutter: ">=3.3.0"
  sdk: ">=3.0.0 <4.0.0"
